### ISSUE TITLE
HOW TO USE THE SODS?

### ISSUE THREAD

**Issue by 1937lilizhou** [msantos/sods#4]
hi
msantos，Could you tell me how to use the sods?What do i need to do something when i use it? I run it by readme, but i always fail.Do I need to build a DNS server called a.example.com in the server of sods?

**Comment by msantos** [comment]
Yes, you'll need somewhere to host your sods server, a registered DNS domain and another DNS server to delegate nameserver lookups to your sods server. There is a very old blog article about it here:

http://blog.listincomprehension.com/2009/12/sods-care-and-feeding-of.html

**Comment by 1937lilizhou** [comment]
Thank you very much for your help，I will see it.

**Comment by 1937lilizhou** [comment]
I want to  run it  in a  virtual machine of ubuntu os, then ,i need to set a DNS server  in the ubuntu by  bind9,right?

**Comment by 1937lilizhou** [comment]
hi
msantos,I am so sorry to bother you again ,but i  still can't to use it successful.I guess that i do not understand it .So,i am very want to know that  the process of it.

**Comment by msantos** [comment]
@1937lilizhou it depends if you are serving the dns for your domain yourself or using the registrar's dns. In the dns server for the top level domain, you'd delegate a subdomain with the NS server pointing to your sods server. Basically,  "example.com" has an NS record delegating a subdomain like "sshdns.example.com" to your sods server.

The blog post has all the steps. If you can't get it work, I'd need to see everything you've done so far.

**Comment by 1937lilizhou** [comment]
@msantos Very much for your help
I have do  a few things:
1.I  haveset up a DNS server in the virtual machine of ubuntu os,this is the results of  testing:
root@ubuntu:/# nslookup
> example.com
Server:		192.168.8.100
Address:	192.168.8.100#53

Name:	example.com
Address: 192.168.8.102
> a.example.com
Server:		192.168.8.100
Address:	192.168.8.100#53

Name:	a.example.com
Address: 192.168.8.102
2.This is the configured of SoDS 
a.   /etc/default/sods
OPTIONS="-D -L ssh.server1:22 -L ssh.server2:22 -L 192.168.8.100:22"
 DOMAIN="a.example.com"
b.  /etc/init.d/sods
#!/bin/sh/etc/rc.common
 #Copyright (C) 2006 OpenWrt.org
 START=50
 
 BIN=sods
DEFAULT=/etc/default/$BIN
 CHROOT_D=/var/chroot/sods
 
 start() {
 include /lib/network
 scan_interfaces
 config_load /var/state/network
 config_get ipaddr wan ipaddr
 
 [ -f $DEFAULT ] && . $DEFAULT
 [ ! -d $CHROOT_D ] && mkdir -p $CHROOT_D
 
 $BIN $OPTIONS -i $ipaddr $DOMAIN
 }
 
 stop() {
 killall sods
 }
3.The following are the process :
a.The build of sods:
server:
root@ubuntu:/# cd sods-master/
root@ubuntu:/sods-master# cd sods
root@ubuntu:/sods-master/sods# ./configure 
root@ubuntu:/sods-master/sods# make
cc -DHAVE_ERRX -DHAVE_SEND -g -Wall -o sods sods.c sods_handler.c sods_dns.c sods_io.c         sods_q.c sods_sock.c sods_priv.c sods_err.c base32.c -lresolv
root@ubuntu:/sods-master/sods# 

client:
root@ubuntu:/sods-master# cd sdt/
root@ubuntu:/sods-master/sdt# ./configure 
root@ubuntu:/sods-master/sdt# make
cc -DHAVE_ERRX -DHAVE_URANDOM -g -Wall  -o sdt sdt.c sdt_dns.c sdt_err.c sdt_rand.c base32.c /usr/lib/*/libresolv.a
root@ubuntu:/sods-master/sdt# 

b, The run of sods:
server:
root@ubuntu:/sods-master/sods# sudo ./sods -vvvv -d /tmp -L 127.0.0.1:22 a.example.com
Forwarded sessions = 1
Forward #0: 127.0.0.1:22
sods: bind(ss->s, (struct sockaddr *)&ss->local, sizeof(ss->local)): Address already in use
 client:
root@ubuntu:/sods-master/sdt# ssh -o ProxyCommand="./sdt -r 192.168.8.100 a.example.com" 127.0.0.100
 note:After the run command without any response in client.
Dear msantos,the above is what I do all things.I all the operations are on a host of ubuntu,i  think that  i wrong in some step.But,i am a rookie, i am learing the DNS tunnel,i have not been very understand about a lot of things.Thank for your help again.

**Comment by msantos** [comment]
@1937lilizhou those scripts and configuration need to be customised for your system. The init script, for example, is for OpenWRT, so you'll have to make your own for ubuntu.

Start simple. Make sure another instance of sods is not running. In one terminal window, run sods and in the other, run sdt like outlined here:
https://github.com/msantos/sods#how-do-i-run-it

If that works for you, start sods in the same way on a server and run sdt on another computer. For example:
~~~
ssh -o ProxyCommand="./sdt -r 192.168.8.100 sshdns.a.example.com" 127.0.0.100
~~~

**Comment by 1937lilizhou** [comment]
@msantos Thank you very much for your reply and help,the follow is the process that i run sods in one ubuntu host.
In one terminal widow,i run sods,the process is as follows:
```
root@ubuntu:/sods-master/sods# ./configure 
root@ubuntu:/sods-master/sods# make
cc -DHAVE_ERRX -DHAVE_SEND -g -Wall -o sods sods.c sods_handler.c sods_dns.c sods_io.c         sods_q.c sods_sock.c sods_priv.c sods_err.c base32.c -lresolv
root@ubuntu:/sods-master/sods# sudo ./sods -vvvv -d /tmp -L 127.0.0.1:22 a.example.com^C
root@ubuntu:/sods-master/sods# sudo ./sods -vvvv -d /tmp -L 127.0.0.1:22 a.example.com 
Forwarded sessions = 1
Forward #0: 127.0.0.1:22
sods: bind(ss->s, (struct sockaddr *)&ss->local, sizeof(ss->local)): Address already in use
root@ubuntu:/sods-master/sods#
```
In aother window,i run sdt,the process is as follows:
```
root@ubuntu:/sods-master/sdt# ./configure 
root@ubuntu:/sods-master/sdt# make
cc -DHAVE_ERRX -DHAVE_URANDOM -g -Wall  -o sdt sdt.c sdt_dns.c sdt_err.c sdt_rand.c base32.c /usr/lib/*/libresolv.a
root@ubuntu:/sods-master/sdt# ssh -o ProxyCommand="./sdt -r 127.0.0.1 sshdns.a.example.com" 127.0.0.100
```
In the sdt directory,i input the command:
`ssh -o ProxyCommand="./sdt -r 127.0.0.1 sshdns.a.example.com" 127.0.0.100`
It does not have any reaction，if it is successful, what will it be?

**Comment by 1937lilizhou** [comment]
_ddddc_

**Comment by 1937lilizhou** [comment]
# ddddd

**Comment by 1937lilizhou** [comment]
[xxx](url)

**Comment by 1937lilizhou** [comment]
ccc

- cccc

**Comment by 1937lilizhou** [comment]
- [ ] cccc

**Comment by 1937lilizhou** [comment]
@msantos just now，i  re-tested it
In the server:

> 2017-05-03 08:57:00 		id = 56943: up = 0, down = 2959
> 2017-05-03 08:57:00 Sending: 127.0.0.1
> 2017-05-03 08:57:35 	2959-57445.id-28638.down.sshdns.a.example.com
> 2017-05-03 08:57:35 		id = 56943: up = 0, down = 2959
> 2017-05-03 08:57:35 Sending: 127.0.0.1
> 2017-05-03 08:58:38 	2959-4156.id-28638.down.sshdns.a.example.com
> 2017-05-03 08:58:38 		id = 56943: up = 0, down = 2959
> 2017-05-03 08:58:38 Sending: 127.0.0.1
> 2017-05-03 08:59:41 	2959-20558.id-28638.down.sshdns.a.example.com
> 2017-05-03 08:59:41 		id = 56943: up = 0, down = 2959
> 2017-05-03 08:59:41 Sending: 127.0.0.1
> 2017-05-03 09:00:44 	2959-21797.id-28638.down.sshdns.a.example.com
> 2017-05-03 09:00:44 		id = 56943: up = 0, down = 2959
> 2017-05-03 09:00:44 Sending: 127.0.0.1
> 2017-05-03 09:01:48 	2959-60766.id-28638.down.sshdns.a.example.com
> 2017-05-03 09:01:48 		id = 56943: up = 0, down = 2959
> 2017-05-03 09:01:48 Sending: 127.0.0.1
> 2017-05-03 09:02:51 	2959-33480.id-28638.down.sshdns.a.example.com
> 2017-05-03 09:02:51 		id = 56943: up = 0, down = 2959
> 2017-05-03 09:02:51 Sending: 127.0.0.1
> 2017-05-03 09:03:54 	2959-59429.id-28638.down.sshdns.a.example.com
> 2017-05-03 09:03:54 		id = 56943: up = 0, down = 2959
> 2017-05-03 09:03:54 Sending: 127.0.0.1

**Comment by 1937lilizhou** [comment]
@msantos just now，i  re-tested it
In the server:

> 2017-05-03 08:57:00 		id = 56943: up = 0, down = 2959
> 2017-05-03 08:57:00 Sending: 127.0.0.1
> 2017-05-03 08:57:35 	2959-57445.id-28638.down.sshdns.a.example.com
> 2017-05-03 08:57:35 		id = 56943: up = 0, down = 2959
> 2017-05-03 08:57:35 Sending: 127.0.0.1
> 2017-05-03 08:58:38 	2959-4156.id-28638.down.sshdns.a.example.com
> 2017-05-03 08:58:38 		id = 56943: up = 0, down = 2959
> 2017-05-03 08:58:38 Sending: 127.0.0.1
> 2017-05-03 08:59:41 	2959-20558.id-28638.down.sshdns.a.example.com
> 2017-05-03 08:59:41 		id = 56943: up = 0, down = 2959
> 2017-05-03 08:59:41 Sending: 127.0.0.1
> 2017-05-03 09:00:44 	2959-21797.id-28638.down.sshdns.a.example.com
> 2017-05-03 09:00:44 		id = 56943: up = 0, down = 2959
> 2017-05-03 09:00:44 Sending: 127.0.0.1
> 2017-05-03 09:01:48 	2959-60766.id-28638.down.sshdns.a.example.com
> 2017-05-03 09:01:48 		id = 56943: up = 0, down = 2959
> 2017-05-03 09:01:48 Sending: 127.0.0.1
> 2017-05-03 09:02:51 	2959-33480.id-28638.down.sshdns.a.example.com
> 2017-05-03 09:02:51 		id = 56943: up = 0, down = 2959
> 2017-05-03 09:02:51 Sending: 127.0.0.1
> 2017-05-03 09:03:54 	2959-59429.id-28638.down.sshdns.a.example.com
> 2017-05-03 09:03:54 		id = 56943: up = 0, down = 2959
> 2017-05-03 09:03:54 Sending: 127.0.0.1

In the client:

> root@ubuntu:/sods-master/sdt# ssh -o ProxyCommand="./sdt -r 127.0.0.1 sshdns.a.example.com" 127.0.0.100
> root@127.0.0.100's password: 
> Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-31-generic i686)
> 
>  * Documentation:  https://help.ubuntu.com/
> 
> Last login: Wed May  3 16:24:23 2017 from localhost
> root@ubuntu:~# ls

msantos,I'm sorry to bother you again.Above is my test results，i guess it was a success.But ,i am still a little confused，i do not know how to send a txt text to the server side,could you tell me how to send a thing from the client to the server side?Thank you for your help.

**Comment by 1937lilizhou** [comment]
@msantos just now，i  re-tested it
In the server:

> 2017-05-03 08:57:00 		id = 56943: up = 0, down = 2959
> 2017-05-03 08:57:00 Sending: 127.0.0.1
> 2017-05-03 08:57:35 	2959-57445.id-28638.down.sshdns.a.example.com
> 2017-05-03 08:57:35 		id = 56943: up = 0, down = 2959
> 2017-05-03 08:57:35 Sending: 127.0.0.1
> 2017-05-03 08:58:38 	2959-4156.id-28638.down.sshdns.a.example.com
> 2017-05-03 08:58:38 		id = 56943: up = 0, down = 2959
> 2017-05-03 08:58:38 Sending: 127.0.0.1
> 2017-05-03 08:59:41 	2959-20558.id-28638.down.sshdns.a.example.com
> 2017-05-03 08:59:41 		id = 56943: up = 0, down = 2959
> 2017-05-03 08:59:41 Sending: 127.0.0.1
> 2017-05-03 09:00:44 	2959-21797.id-28638.down.sshdns.a.example.com
> 2017-05-03 09:00:44 		id = 56943: up = 0, down = 2959
> 2017-05-03 09:00:44 Sending: 127.0.0.1
> 2017-05-03 09:01:48 	2959-60766.id-28638.down.sshdns.a.example.com
> 2017-05-03 09:01:48 		id = 56943: up = 0, down = 2959
> 2017-05-03 09:01:48 Sending: 127.0.0.1
> 2017-05-03 09:02:51 	2959-33480.id-28638.down.sshdns.a.example.com
> 2017-05-03 09:02:51 		id = 56943: up = 0, down = 2959
> 2017-05-03 09:02:51 Sending: 127.0.0.1
> 2017-05-03 09:03:54 	2959-59429.id-28638.down.sshdns.a.example.com
> 2017-05-03 09:03:54 		id = 56943: up = 0, down = 2959
> 2017-05-03 09:03:54 Sending: 127.0.0.1

In the client:

> root@ubuntu:/sods-master/sdt# ssh -o ProxyCommand="./sdt -r 127.0.0.1 sshdns.a.example.com" 127.0.0.100
> root@127.0.0.100's password: 
> Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-31-generic i686)
> 
>  * Documentation:  https://help.ubuntu.com/
> 
> Last login: Wed May  3 16:24:23 2017 from localhost
> root@ubuntu:~# ls

msantos,I'm sorry to bother you again.Above is my test results，i guess it was a success.But ,i am still a little confused，i do not know how to send a txt text to the server side,could you tell me how to send a thing from the client to the server side?Thank you for your help.

**Comment by msantos** [comment]
The error message indicated another service was using port 53:
~~~
# sudo ./sods -vvvv -d /tmp -L 127.0.0.1:22 a.example.com 
Forwarded sessions = 1
Forward #0: 127.0.0.1:22
sods: bind(ss->s, (struct sockaddr *)&ss->local, sizeof(ss->local)): Address already in use
~~~

Yes, this indicates you've successfully logged in via the dns tunnel over the loopback:
~~~
root@127.0.0.100's password:
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 4.4.0-31-generic i686)
~~~

> i do not know how to send a txt text to the server side,could you tell me how to send a thing from the client to the server side?

Not clear what you're asking. Next step is to run sods and sdt on different systems and go directly from sdt to sods as in https://github.com/msantos/sods/issues/4#issuecomment-298790369

Then, if you don't have one, you will need to register a domain name and set up the zone records.

**Comment by 1937lilizhou** [comment]
Dear  msantos ,
Pardon me, i am not good at  English.My means is that  the end result of test is that I log in to the sods from sdt,right?Can not it send and receive data like OzymanDNS?

**Comment by msantos** [comment]
Yes, you are sending ssh data via the tunnel. You could use it to send arbitrary data to a TCP port but since the data is sent via an intermediary DNS server, we encrypt the data using ssh.

Instead you can use ssh to proxy whatever ports you want, e.g., using the ssh socks proxy (-D) or port forwarding (-L). See the ssh(1) man page for details.

**Comment by 1937lilizhou** [comment]
hi msantos,
Thank you for your help, I will run sods on different system, if I have some problems,i will tell you.

**Comment by 1937lilizhou** [comment]
hi msantos,
I run the sods in a server,then , the following error occurred

- [root@master sods]# sudo ./sods -vvvv -d /tmp -L 210.40.16.123:22 a.example.com
- Forwarded sessions = 1
- Forward #0: 210.40.16.123:22
- sods: group does not exist: nogroup
- sods: Could not drop privs
Could you tell me  the reason?

**Comment by 1937lilizhou** [comment]
hi msantos,
Could you tell me the  principle of sods，i would love to know its flow of data. I have seen the source code,but i did not really understand its principles.

**Comment by msantos** [comment]
* regarding the error (https://github.com/msantos/sods/issues/4#issuecomment-299695226)
  The sods daemon is attempting to run as a non-root user. Use the "-u" and "-g" options to control which user sods should run as:
~~~
sods, 0.7.0
usage: sods <option> <domain name>
             -c     max connections
             -D     run as a daemon
             -d     chroot directory
             -g     unprivileged group
             -i     local IP address
             -L     forward socket: <host>:<port>
             -p     port
             -u     unprivileged user
             -v     verbose
             -x     connection timeout
~~~
* regarding how sods works (https://github.com/msantos/sods/issues/4#issuecomment-299706198), the best way to learn how it works is to sniff the DNS traffic. 

The protocol is basically the same as ozymandns with a few extensions. Some googling should turn up more information. For example, https://dnstunnel.de

**Comment by 1937lilizhou** [comment]
hi msantos,
I run the sods in a server,then , the following error occurred

- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
- @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
- @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
- IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
- Someone could be eavesdropping on you right now (man-in-the-middle attack)!
- It is also possible that a host key has just been changed.
- The fingerprint for the RSA key sent by the remote host is
- f7:fa:d7:29:4a:3e:5f:72:71:43:95:56:b3:a6:e0:8e.
- Please contact your system administrator.
- Add correct host key in /root/.ssh/known_hosts to get rid of this message.
- Offending ECDSA key in /root/.ssh/known_hosts:1
-   remove with: ssh-keygen -f "/root/.ssh/known_hosts" -R 127.0.0.100
- RSA host key for 127.0.0.100 has changed and you have requested strict checking.
- Host key verification failed.
Could you tell me the reason?

**Comment by 1937lilizhou** [comment]
hi msantos,
I run the sods in a server,then ,i have successfully logged in to this server that run the sods.
# In the sods directory  .It in centos .
I enter the following command

- sudo ./sods -vvvv -d /tmp -L 127.0.0.1:22 a.example.com

# In the sdt directory.It in ubuntu .
I enter the following command

- ssh -o ProxyCommand="./sdt -r 210.40.19.10 sshdns.a.example.com" 210.40.19.10

Through the above steps,i successfully logged into the 210.40.19.10 this server.But,i always feel that this is not really a success,because my DNS server did not build a success.I feel that I just connected to the server through ssh only, but did not use the DNS tunnel。

**Comment by msantos** [comment]
@1937lilizhou verify by running sdt and sods in verbose mode (-vvv)

Once logged in running "netstat -an |grep 22" should show your ssh connection from localhost.

**Comment by 1937lilizhou** [comment]
Just now，i run sdt and sods in verbose mode. In sdt,it display "host name lookup failure".In sods,it display "rejecting request for domain: example.com".
msantos,if i have already registered a domain name named zhullx.xyz,here is the record I added:

- dns.zhullx.xyz NS zhou.zhullx.xyz
- zhou.zhullx.xyz A 210.40.19.10
the IP address is entered into the server running sods,Is this configuration correct?

**Comment by 1937lilizhou** [comment]
hi,msantos
First,the sods server listens 53 port.
Second ,when the client transfers data to the sods server,the sods server The sods server sends sends data to port 22.
Last,data is  spread from the 22 port to the client.
Is the above process correct?If it is right, how it is achieved?

**Comment by msantos** [comment]
Yes, that is correct. Basically:
~~~
ssh -> stdout -> sdt -> (DNS traffic) -> sods ->  (TCP from localhost to port 22) -> sshd
~~~
sdt encodes the data read from stdin as the domain name in DNS A records and sends it to the local DNS resolver which does the actual request to the sods server.

sods decodes the DNS requests and writes the data to sshd over a TCP socket.

For data sent from sods to sdt, sdt polls the sods by sending, by default, a request for a TXT record. Each poll causes sods to do a read on the TCP connection to sshd. The read is encoded in the reply to the TXT record request.

**Comment by 1937lilizhou** [comment]
hi,msantos,
That means sending ssh data with DNS tunnel，right?

**Comment by 1937lilizhou** [comment]
hi,msantos,
That means sending ssh data with DNS tunnel，right?
In addition to send ssh data,are there other interesting features?Such as, Can i use it online  like dns2tcp?

**Comment by msantos** [comment]
@1937lilizhou yes, see comments https://github.com/msantos/sods/issues/4#issuecomment-298918827 and https://github.com/msantos/sods/issues/4#issuecomment-300491111

**Comment by 1937lilizhou** [comment]
msantos,
I am still a little confused，could you give me I give an example?

**Comment by msantos** [comment]
@1937lilizhou sorry not clear what you are asking. sdt/sods are fairly small programs, so I suggest reading through the code and then running them in verbose mode/sniffing the traffic to see the protocol format.

If you still have questions, it may help to review these articles:
http://www.catb.org/esr/faqs/smart-questions.html
https://www.chiark.greenend.org.uk/~sgtatham/bugs.html

It is difficult to answer open ended questions. I don't want to discourage asking questions, but asking clarification for a specific, technical issue after you've done a little work will result both in better questions and better answers. 

I am going to close this issue. If you run into any more problems or have any suggestions or questions, please feel free to open a new issue!

**Comment by 1937lilizhou** [comment]
Ok, msantos, thank you very much for your help, because of your help, i learned a lot, thank you again!
