### ISSUE TITLE
Make in Termux

### ISSUE THREAD

**Issue by ASHANTENNA** [msantos/sods#6]
It seems like the 'configure' file is not configured yet for android in Termux, I'm getting this error :
`cc -DHAVE_ERRX -DHAVE_URANDOM -g -Wall  \
    -Wall -Wextra -pedantic \
    -Wshadow -Wpointer-arith -Wcast-qual \
    -Wstrict-prototypes -Wmissing-prototypes \
    -I../common \
    -o sdt sdt.c sdt_dns.c sdt_err.c sdt_rand.c base32.c ../common/strtonum.c /data/data/com.termux/files/usr/lib/*/libresolv.a \
    -Wl,-z,relro,-z,now -Wl,-z,noexecstack
cc: error: no such file or directory: '/data/data/com.termux/files/usr/lib/*/libresolv.a'`

**Comment by msantos** [comment]
@ASHANTENNA Sorry, I missed this issue.

Looks like libresolv.a is distributed with termux glibc now: https://github.com/termux/glibc-packages

```
pkg install glibc-repo -y
pkg install glibc-runner -y
pkg install gcc-glibc -y
glibc-runner -s

# clone sods and change to the sdt directory
./configure
```

Modify the generated Makefile to use the termux glibc paths:

```
< STATIC_LIB=/usr/lib/*/libresolv.a
---
> STATIC_LIB=/data/data/com.termux/files/usr/glibc/lib/libresolv.a
7c7
< LIB=
---
> LIB=-L /data/data/com.termux/files/usr/glibc/lib
14a15
>     -I /data/data/com.termux/files/usr/glibc/include \
```

Then run:

```
make
```

**Comment by ASHANTENNA** [comment]
no problem bro, I have fixed the issue, thanks

Le lun. 14 oct. 2024, 19:54, Michael Santos ***@***.***> a
écrit :

**Comment by ASHANTENNA** [comment]
@msantos Many big thanks to you ❤️, issue solved
